PORT: 9000
PREFIX: api

# token过期时间为7天
tokenExpire: 7

# 数据库配置
database:
  type: mysql
  host: localhost
  port: 3306
  database: nest_demo
  username: root
  password: 12345678
  charset: utf8mb4
  loc: Asia/Shanghai
  logging: true
  synchronize: true